schema_version = "1.0.0"

# Basic Add-on Info
id = "kitsune_source_tools"
name = "Kitsune Source Tools"
version = "0.2.95"
tagline = "A forked of BlenderSourceTools, an Importer and exporter for Valve Software's Source Engine Models"
maintainer = "Tom Edwards (BlenderSourceTools) & Toppi (KitsuneSourceTools)"
type = "add-on"
website = "http://steamcommunity.com/groups/BlenderSourceTools"

# Blender Compatibility
blender_version_min = "4.5.0"

# Licensing
license = [
    "SPDX:GPL-2.0-or-later"
]

# Permissions
permissions = ["files", "network"]

# Optional Metadata
tags = [
    "Import-Export",
    "Source Engine",
    "Animation",
    "Texture Conversion"
]

wheels = [
    "./wheels/pillow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-macosx_10_10_x86_64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl",
    "./wheels/pillow-12.0.0-cp311-cp311-win_amd64.whl",
]